### PR TITLE
Added with sexp serialization to pattern type.

### PR DESCRIPTION
**Pull request by robertsoule**

### CODE REVIEW

**Comment by seliopou** [comment]
If this is merged, than #180 should be closed since it's mostly redundant.

**Comment by tudang** [comment]
The only different is type of m_mask. In #180 option is replaced by sexp_option to to remove empty fields of pattern in s-expression output.

**Comment by arjunguha** [comment]
So should we merge #180 instead of this one? Does @robertsoule have a preference?

**Comment by robertsoule** [comment]
No comment, @arjunguha. Please merge.

**Pull request merged**
